# Official MCP servers

## Built-in servers
# https://github.com/modelcontextprotocol/servers/blob/main/src

# Time and timezone conversion capabilities
[mcp.providers.time]
enabled = true
command = "uv"
args = ["tool", "run", "mcp-server-time"]
env = {}

# Tools to read, search, and manipulate Git repositories
[mcp.providers.git]
enabled = true
command = "uv"
args = ["tool", "run", "mcp-server-git"]
env = {}

# Web content fetching and conversion for efficient LLM usage
[mcp.providers.fetch]
enabled = true
command = "uv"
args = ["tool", "run", "mcp-server-fetch"]
env = {}

# Secure file operations with configurable access controls
[mcp.providers.filesystem]
enabled = true
command = "pnpm"
args = ["dlx", "@modelcontextprotocol/server-filesystem@latest"]
env = {}

# Dynamic and reflective problem-solving through thought sequences
[mcp.providers.sequential-thinking]
enabled = true
command = "pnpm"
args = ["dlx", "@modelcontextprotocol/server-sequential-thinking@latest"]
env = {}

# Knowledge graph-based persistent memory system
[mcp.providers.memory]
enabled = true
command = "pnpm"
args = ["dlx", "@modelcontextprotocol/server-memory@latest"]
env = {}

# Third-Party MCP servers

# grep.app
[mcp.providers.grep_app]
enabled = true
type = "remote"
url = "https://mcp.grep.app"
env = {}

# Up-to-date code documentation for LLMs and AI code editors
# https://github.com/upstash/context7
[mcp.providers.context7]
enabled = true
type    = "stdio"
command = "pnpm"
args = ["dlx", "@upstash/context7-mcp@latest", "--api-key", "$CONTEXT7_API_KEY"]
env = {}

# MCP server that provides information about mise-managed development environment (experimental)
# https://mise.jdx.dev/mcp.html
[mcp.providers.mise]
enabled = true
type    = "stdio"
command = "mise"
args = ["mcp"]
env = {}

# Enable AI coding assistants to debug web pages directly in Chrome, providing runtime insights and debugging capabilities
# https://github.com/ChromeDevTools/chrome-devtools-mcp
[mcp.providers.chrome-devtools]
enabled = true
type    = "stdio"
command = "pnpm"
args = ["dlx", "chrome-devtools-mcp@latest"]
env = {}

[mcp.providers.playwright-mcp]
enabled = true
type    = "stdio"
command = "pnpm"
args = ["dlx", "@playwright/mcp@latest"]
env = {}

# A powerful coding agent toolkit providing semantic retrieval and editing capabilities (MCP server & other integrations)
# https://oraios.github.io/serena
[mcp.providers.serena]
enabled = true
type    = "stdio"
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena ", "serena", "start-mcp-server", "--context", "ide-assistant", "--enable-web-dashboard", "false"]
env = {}
