# -*-mode:toml-*- vim:ft=toml

# Runtime

# tombi: lint.rules.key-not-allowed.disabled = true
## Node.js
[mise.langs.node]
enabled  = true
versions = ["24"]

[mise.langs.pnpm]
enabled  = true
versions = ["10"]

[mise.langs.deno]
enabled  = true
versions = ["2"]

[mise.langs.bun]
enabled  = true
versions = ["1"]

## Go
[mise.langs.go]
enabled  = true
versions = ["latest"]

## Python
[mise.langs.python]
enabled  = true
versions = ["3.14"]

[mise.langs.uv]
enabled  = true
versions = ["latest"]

## Ruby
[mise.langs.ruby]
enabled  = true
versions = ["3.4"]
