# -*-mode:toml-*- vim:ft=toml

# Runtime

# tombi: lint.rules.key-not-allowed.disabled = true
## Node.js
[mise.langs.node]
enabled  = true
versions = ["24"]

[mise.langs.pnpm]
enabled  = true
versions = ["10"]

[mise.langs.deno]
enabled  = true
versions = ["2"]

[mise.langs.bun]
enabled  = true
versions = ["1"]

## Go
[mise.langs.go]
enabled  = true
versions = ["latest"]

## Python
[mise.langs.python]
enabled  = true
versions = ["3.14"]

[mise.langs.uv]
enabled  = true
versions = ["latest"]

## Ruby
[mise.langs.ruby]
enabled  = true
versions = ["3.4"]


## CLI via aqua
# TODO: Separate CLI tool config with categories later
### Terminal
[[mise.tools]]
"aqua:zellij-org/zellij"       = "latest" # Terminal multiplexer

### Editor
[[mise.tools]]
"aqua:neovim/neovim"           = "latest" # Hyper extensive editor

### Build
[[mise.tools]]
"aqua:Kitware/CMake"           = "latest" # build system generator

[[mise.tools]]
"aqua:casey/just"              = "latest" # Just a command runner

### Shell
[[mise.tools]]
"aqua:rossmacarthur/sheldon"   = "latest" # Shell plugin manager

[[mise.tools]]
"aqua:starship/starship"       = "latest" # Shell prompt

### alternative command
[[mise.tools]]
"aqua:ajeetdsouza/zoxide"      = "latest" # Smarter cd command

[[mise.tools]]
"aqua:sharkdp/bat"             = "latest" # `cat` alternative

[[mise.tools]]
"aqua:sharkdp/fd"              = "latest" # `find` alternative

[[mise.tools]]
"aqua:BurntSushi/ripgrep"      = "latest" # `grep` alternative

[[mise.tools]]
"aqua:phiresky/ripgrep-all"    = "latest" # extended `ripgrep` for pdf, docs, archives, img, movies, etc

[[mise.tools]]
"aqua:junegunn/fzf"            = "latest" # Fuzzy finder

[[mise.tools]]
"aqua:ClementTsang/bottom"     = "latest" # Process monitor

[[mise.tools]]
"aqua:watchexec/watchexec"     = "latest" # Modify detector

[[mise.tools]]
"aqua:sxyazi/yazi"             = "latest" # Modern TUI explorer

[[mise.tools]]
"aqua:Byron/dua-cli"           = "latest" # Disk usage

[[mise.tools]]
"aqua:sharkdp/hyperfine"       = "latest" # Benchmark tool

[[mise.tools]]
"aqua:svenstaro/genact"        = "latest" # nonsense activity generator

[[mise.tools]]
"aqua:tealdeer-rs/tealdeer"    = "latest" # Too long don't read

[[mise.tools]]
"github:yt-dlp/yt-dlp"         = "latest" # Downloader

### Editor
[[mise.tools]]
"aqua:tree-sitter/tree-sitter" = "latest" # language parser

### Git
[[mise.tools]]
"aqua:o2sh/onefetch"           = "latest" # Repository information

[[mise.tools]]
"aqua:gitui-org/gitui"         = "latest" # Git TUI

[[mise.tools]]
"aqua:dandavison/delta"        = "latest" # `git-delta`

[[mise.tools]]
"aqua:git-lfs/git-lfs"         = "latest" # `git` large file storage extension

[[mise.tools]]
"aqua:orhun/git-cliff"         = "latest" # Changelog generator

[[mise.tools]]
"aqua:simonwhitaker/gibo"      = "latest" # `.gitignore` boilerplates

[[mise.tools]]
"npm:commitizen"                = "latest"

[[mise.tools]]
"npm:cz-conventional-changelog" = "latest"

### GitHub
[[mise.tools]]
"aqua:cli/cli"                  = "latest" # `gh` command: GitHub CLI

[[mise.tools]]
"aqua:x-motemen/ghq"            = "latest" # Remote repository manager

[[mise.tools]]
"aqua:suzuki-shunsuke/pinact"   = "latest" # Version Pinner for GitHub Actions

### Dotfiles
[[mise.tools]]
"aqua:twpayne/chezmoi"          = "latest" # Dotfiles manager

### Linter / Formatter
[[mise.tools]]
"aqua:mvdan/sh"                 = "latest" # Shell formatter

[[mise.tools]]
"aqua:astral-sh/ruff"           = "latest" # Python Linter / Formatter

[[mise.tools]]
"aqua:biomejs/biome"            = "latest" # eslint & prettier replacement

[[mise.tools]]
"aqua:google/yamlfmt"           = "latest" # YAML formatter

[[mise.tools]]
"aqua:tombi-toml/tombi"         = "latest" # TOML Linter / Formatter / Language Server

[[mise.tools]]
"aqua:rhysd/actionlint"         = "latest" # YAML Linter for GitHub Actions workflows

[[mise.tools]]
"aqua:golangci/golangci-lint"   = "latest" # Go linter aggregator

[[mise.tools]]
"aqua:hadolint/hadolint"        = "latest" # Dockerfile Linter

[[mise.tools]]
"aqua:JohnnyMorganz/StyLua"     = "latest" # Lua Linter

[[mise.tools]]
"aqua:mrtazz/checkmake"         = "latest" # Makefile Linter

### Database
[[mise.tools]]
"aqua:jorgerojas26/lazysql"     = "latest" # SQL with TUI

### Data Analysis
[[mise.tools]]
"github:medialab/xan"           = "latest" # CSV visualization toolkit

### Documents
[[mise.tools]]
"github:jgm/pandoc"             = "latest" # Universal markup converter

### JSON / YAML / Markdown
[[mise.tools]]
"aqua:jqlang/jq"                = "latest" # CLI processor for JSON

[[mise.tools]]
"aqua:mikefarah/yq"             = "latest" # CLI processor for YAML, JSON, XML, CSV, TSV, TOML, HCL, base64

[[mise.tools]]
"aqua:charmbracelet/glow"       = "latest" # Render markdown on the CLI

### Security
[[mise.tools]]
"aqua:FiloSottile/age"          = "latest" # Simple encrypt / decrypt tool

[[mise.tools]]
"aqua:gitleaks/gitleaks"        = "latest" # tool for detecting secrets like passwords, API keys, and tokens in repos

### Container
[[mise.tools]]
"aqua:lima-vm/lima"                  = "latest" # Linux virtual machines, with a focus on running containers

[[mise.tools]]
"aqua:abiosoft/colima"               = "latest" # Container runtimes on macOS (and Linux) with minimal setup

[[mise.tools]]
"aqua:docker/cli"                    = "latest" # Docker CLI

[[mise.tools]]
"aqua:docker/buildx"                 = "latest" # Docker CLI plugin for extended build capabilities with BuildKit

[[mise.tools]]
"aqua:docker/compose"                = "latest" # Define and run multi-container applications with Docker

[[mise.tools]]
"aqua:wagoodman/dive"                = "latest" # A tool for exploring each layer in a docker image

### AI tools
[[mise.tools]]
"aqua:sst/opencode"      = "latest" # The open source coding agent.

[[mise.tools]]
"npm:@google/gemini-cli" = "latest" # An open-source AI agent that brings the power of Gemini

### Others
[[mise.tools]]
"go:github.com/mrusme/reader" = "latest" # A lightweight tool offering better readability of web pages
