# -*-mode:toml-*- vim:ft=toml

[packages]

[packages.brew]
core  = [ "gnutls", "coreutils" ]
disk  = [ "diskonaut" ]
mac   = [ "pinentry-mac" ]
linux = [ "util-linux", "cups" ]
shell    = [ "fish" ]
terminal = [ "tmux", "fastfetch" ]
command  = [ "eza" ]
vcs      = [ "git", "tig" ]
security = [ "openssl", "gnupg" ]
browser  = [ "w3m", "newsboat" ]
network  = [ "sniffnet" ]
downloader  = [ "wget", "curl", "aria2" ]
runtime  = [ "mise" ]
lua      = [ "luarocks" ]
kubernetes = [ "kubernetes-cli", "helm", "k3d", "k3sup", "k9s", "kind", "krew", "kubectx", "kustomize" ]
media  = [ "ffmpeg-full" ]
image  = [ "imagemagick", "exiftool" ]
devops = [ "terraform", "awscli", "azure-cli" ]
update = [ "topgrade" ]

[packages.cask]
maintenance = [ "onyx", "appcleaner" ]
language    = [ "monolingual" ]
dictionary  = []
finder   = [ "symboliclinker" ]
keyboard = [ "karabiner-elements" ]
ime      = [ "google-japanese-ime" ]
editor   = [ "coteditor" ]
font     = [ "font-codicon", "font-jetbrains-mono-nerd-font", "font-plemol-jp-nf", "font-udev-gothic-nf" ]
archive   = [ "suspicious-package" ]
launcher  = [ "raycast" ]
browser   = [ "google-chrome", "brave-browser", "firefox" ]
previewer = []
terminal  = [ "wezterm", "ghostty" ]
ide       = [ "visual-studio-code" ]
devops    = [ "google-cloud-sdk" ]
diagram   = [ "drawio" ]
tex       = [ "basictex" ]
graphics  = [ "blender" ]
player    = [ "iina", "vlc", "spotify" ]
audio     = [ "blackhole-2ch" ]
chat      = [ "beeper" ]
storage   = [ "dropbox" ]

[[packages.mas]]
name = "Keka"
id   = 470158793

[[packages.mas]]
name = "The Unarchiver"
id   = 425424353

[[packages.mas]]
name = "WinArchiver"
id   = 414855915

[[packages.mas]]
name = "LINE"
id   = 539883307

[[packages.mas]]
name = "Pages"
id   = 409201541

[[packages.mas]]
name = "Numbers"
id   = 409203825

[[packages.mas]]
name = "Vimari"
id   = 1480933944
