# -*-mode:toml-*- vim:ft=toml

[packages]
npm    = [ "neovim", "commitizen", "cz-conventional-changelog", "npm-check-updates", "mcp-hub", "@google/gemini-cli" ]
go     = []
python = [ "mcp-cli", "mcp-server-time", "mcp-server-git", "mcp-server-fetch", "mcp-server-docker", "markitdown-mcp" ]
gem    = []

[packages.brew]
core  = [ "gnutls", "coreutils" ]
disk  = [ "diskonaut" ]
mac   = [ "pinentry-mac" ]
linux = [ "util-linux", "cups" ]
shell    = [ "fish" ]
terminal = [ "tmux", "fastfetch" ]
command  = [ "eza" ]
vcs      = [ "git", "tig" ]
security = [ "openssl", "gnupg" ]
browser  = [ "w3m", "newsboat" ]
network  = [ "sniffnet" ]
downloader  = [ "wget", "curl", "aria2", "yt-dlp", "rclone" ]
runtime  = [ "mise" ]
rust     = [ "rustup-init" ]
lua      = [ "luarocks" ]
kubernetes = [ "kubernetes-cli", "helm", "k3d", "k3sup", "k9s", "kind", "krew", "kubectx", "kustomize" ]
media  = [ "ffmpeg", "media-info" ]
image  = [ "imagemagick", "exiftool" ]
devops = [ "terraform", "awscli", "azure-cli" ]
update = [ "topgrade" ]

[packages.cask]
tap = [ "Homebrew/services" ]
maintenance = [ "onyx", "appcleaner" ]
language    = [ "monolingual" ]
dictionary  = []
finder   = [ "syntax-highlight", "webpquicklook", "symboliclinker" ]
keyboard = [ "karabiner-elements" ]
ime      = [ "google-japanese-ime" ]
editor   = [ "coteditor" ]
font     = [ "font-codicon", "font-jetbrains-mono-nerd-font", "font-plemol-jp-nf", "font-udev-gothic-nf" ]
archive   = [ "suspicious-package" ]
launcher  = [ "raycast" ]
browser   = [ "google-chrome", "brave-browser", "firefox" ]
previewer = []
terminal  = [ "wezterm", "ghostty" ]
ide       = [ "visual-studio-code" ]
devops    = [ "google-cloud-sdk" ]
database  = [ "tableplus" ]
diagram   = [ "drawio" ]
tex       = [ "basictex" ]
note      = [ "obsidian" ]
graphics  = [ "blender" ]
player    = [ "iina", "vlc", "spotify" ]
audio     = [ "audacity", "blackhole-2ch", "ivolume" ]
osc       = [ "touchosc-bridge", "touchosc-editor" ]
broadcast = [ "obs" ]
network   = [ "tunnelbear", "transmission" ]
chat      = [ "slack", "discord", "franz" ]
storage   = [ "dropbox" ]

[[packages.mas]]
name = "Keka"
id   = 470158793

[[packages.mas]]
name = "The Unarchiver"
id   = 425424353

[[packages.mas]]
name = "WinArchiver"
id   = 414855915

[[packages.mas]]
name = "LINE"
id   = 539883307

[[packages.mas]]
name = "Pages"
id   = 409201541

[[packages.mas]]
name = "Numbers"
id   = 409203825

[[packages.mas]]
name = "Vimari"
id   = 1480933944
