# -*-mode:toml-*- vim:ft=toml

################################################################################
# Zsh
################################################################################
[sheldon.zsh]

[[sheldon.zsh.plugins]]
github = "romkatv/zsh-defer"

[[sheldon.zsh.plugins]]
name   = "bashcompinit"
inline = "autoload -Uz bashcompinit && zsh-defer bashcompinit"

[[sheldon.zsh.plugins]]
name   = "compinit"
inline = "autoload -Uz compinit && zsh-defer compinit"

[[sheldon.zsh.plugins]]
name   = "colors"
inline = "autoload -Uz colors && zsh-defer colors"

[[sheldon.zsh.plugins]]
github = "zsh-users/zsh-autosuggestions"
defer  = true

[[sheldon.zsh.plugins]]
github = "zsh-users/zsh-syntax-highlighting"
defer  = true

[[sheldon.zsh.plugins]]
github = "zsh-users/zsh-completions"
defer  = true

[[sheldon.zsh.plugins]]
github = "zsh-users/zsh-history-substring-search"
defer  = true

[[sheldon.zsh.plugins]]
github = "hlissner/zsh-autopair"

[[sheldon.zsh.plugins]]
github = "olets/zsh-abbr"

[[sheldon.zsh.plugins]]
github = "z-shell/zsh-eza"

[[sheldon.zsh.plugins]]
github = "jeffreytse/zsh-vi-mode"
