# -*-mode:toml-*- vim:ft=toml

[wezterm]
themes = [
  "One Dark (Gogh)",
  "One Half Black (Gogh)",
  "Oxocarbon Dark (Gogh)",
  "Thayer Bright (Gogh)",
  "Tokyo Night Storm (Gogh)",
]
images = [
  "daft-punk-music-retro-style-wallpaper.jpg",
  "daft-punk-music-black-background-helmet-wallpaper.jpg",
  "daft-punk-punk-edm-music-wallpaper.jpg",
]
