# -*-mode:toml-*- vim:ft=toml

[zellij.mode]
fg = "#1A1B26"
bg = "#383E5A"

[zellij.locked]
bg = "red"

[zellij.normal]
bg = "blue"

[zellij.resize]
bg = "magenta"

[zellij.scroll]
bg = "cyan"

[zellij.pane.normal]
fg = "black"
bg = "magenta"

[zellij.pane.rename]
fg = "white"
bg = "magenta"

[zellij.session]
bg = "yellow"

[zellij.tmux]
bg = "yellow"

[zellij.tab.normal]
fg = "#A9B1D6"
bg = "green"

[zellij.tab.active]
fg = "green"

[zellij.tab.rename]
bg = "green"

[zellij.tab.separator]
fg = "grey"
bg = "purple"
