# -*-mode:toml-*- vim:ft=toml

[zellij.colors]
fg      = "#a0a8b7"
bg      = "#282c34"
black   = "#0e1013"
grey    = "#535965"
white   = "#f0f0f0"
red     = "#e55561"
orange  = "#cc9057"
yellow  = "#e2b86b"
green   = "#8ebd6b"
blue    = "#4fa6ed"
cyan    = "#48b0bd"
purple  = "#bf68d9"
magenta = "#a626a4"
